---
- hosts: dev
  tasks:
  - name: Install nginx
    ansible.builtin.yum:
      name: nginx
      state: present
  - name: Start and Enable Nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      - name: Change port number
    ansible.builtin.template:
      src: /root/playbooks/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
  - name: Change port number
    ansible.builtin.template:
      src: /root/playbooks/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    vars:
      port: 80





